language: python

python:
  - '3.4'
  - '2.7'

before_install:
  - sudo apt-get install -y espeak python-espeak python-dbus jackd2

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - nosetests  --with-coverage --cover-package=chatterbot_voice

after_success:
  - coveralls
