sudo: false
language: python

python:
  - '3.4'
  - '2.7'
  
addons:
  apt:
    packages:
      - xvfb
      - espeak
      - python-espeak
      #- dbus
      #- python-dbus
      #- python-dbus-dev
      #- libjack-jackd2-0
      #- jackd2
      - libpulse-dev
      #- portaudio19-dev
      #- libsonic-dev

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - pip install coveralls flake8
  - pip install -r requirements.txt

script:
  - flake8
  - nosetests  --with-coverage --cover-package=chatterbot_voice

after_success:
  - coveralls
