language: python

python:
  - '3.4'
  - '2.7'

before_install:
  - sudo apt-get install -y espeak python-espeak
  - sudo apt-get install -y dbus python-dbus python-dbus-dev
  - sudo apt-get install -y jackd2

install:
  - pip install coveralls flake8
  - pip install -r requirements.txt

script:
  - flake8
  - nosetests  --with-coverage --cover-package=chatterbot_voice

after_success:
  - coveralls
