language: python

python:
  - '3.4'
  - '2.7'
  
addons:
  apt:
    packages:
      - xvfb

before_install:
  - sudo apt-get install -y espeak python-espeak
  - sudo apt-get install -y dbus python-dbus python-dbus-dev
  - sudo apt-get install -y jackd2

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - pip install coveralls flake8
  - pip install -r requirements.txt

script:
  - flake8
  - nosetests  --with-coverage --cover-package=chatterbot_voice

after_success:
  - coveralls
